spring:
  zipkin:
    base-url: http://localhost:9411spring
  application:
    name: vangen-zuul
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 7999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: vangen-Client
