spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: vangen-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false