server:
  port: 8151

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: vangen-Client

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
feign:
  hystrix:
    enabled: true
