spring:
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8051
spring:
  application:
    name: vangen-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
