server:
  port: 8051
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vangencloud?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  application:
    name: vangen-service
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
mconfig:
  swagger-ui-open: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
