spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: vangen-eureka
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/