spring:
  application:
    name: vangen-zuul
server:
  port: 7999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: vangen-Client
